# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: false
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pdftk
r_packages:
  - covr
script:
  - sed -i '/tests/d' ./.Rbuildignore
  - R CMD build .
  - R CMD check *tar.gz
after_success:
  - Rscript -e 'library(covr); codecov()'
